#ifndef CONSTANTS_H
#define CONSTANTS_H

#define PORT 8080 
#define DATA_SIZE 64 
#define TIMEOUT 2
#define NR_OF_TIMEOUTS_ALLOWED 5
#define WINDOW_SIZE 64
#define APPLICATION_SIMULATOR 1
#define NUMBER_OF_LOOPS 1
#define PACKETS_TO_SEND 7
#define USING_SELECTIVE_REPEAT 1
#endif